#
#  ▄▀█ █░░ ▄▀█ █▀▀ █▀█ █ ▀█▀ ▀█▀ █▄█
#  █▀█ █▄▄ █▀█ █▄▄ █▀▄ █ ░█░ ░█░ ░█░
#

[env]
TERM = "xterm-256color"

[font]
size = 11.0
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"

[window]
opacity   = 1.0
padding.x = 10
padding.y = 10

[general]
import = ["/home/flin/.dotfiles/alacritty/colors/catppuccin-macchiato.toml"]
