#
#  ▄▀█ █░░ ▄▀█ █▀▀ █▀█ █ ▀█▀ ▀█▀ █▄█
#  █▀█ █▄▄ █▀█ █▄▄ █▀▄ █ ░█░ ░█░ ░█░
#
#  Frederik Lind (2024)

[env]
TERM = "xterm-256color"

[font]
size = 10.5
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"


[window]
opacity = 1
padding.x = 5
padding.y = 4

[general]
import = ["/home/flin/.dotfiles/alacritty/colors/catppuccin-macchiato.toml"]
