[colors.primary]
background = "#24283b"
foreground = "#bac2de"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "#24273a"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#838ba7"
background = "#303446"

[colors.normal]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.dim]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[[colors.indexed_colors]]
index = 16
color = "#f5a97f"

[[colors.indexed_colors]]
index = 17
color = "#f4dbd6"
