# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references
# the colours from your terminal theme: 
#
# Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, 
# LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.

theme:
  active: "139, 213, 202" # current playing song in list
  banner: LightCyan # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: Red # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: "139, 213, 202" # hovered pane border
  inactive: "91, 96, 120" # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: "54, 58, 79" # filled-in part of the progress bar
  playbar_progress_text: "139, 213, 202" # song length and time played/left indicator in the progress bar
  playbar_text: "139, 213, 202" # artist name in player pane
  selected: LightCyan # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "138, 173, 244" # text in panes
  header: "139, 213, 202" # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 250
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: true
  # Controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
  # Disables the responsive layout that makes the search bar smaller on bigger
  # screens and enforces a wide search bar
  enforce_wide_search_bar: true
  # Determines the text icon to display next to "liked" Spotify items, such as
  # liked songs and albums, or followed artists. Can be any length string.
  # These icons require a patched nerd font.
  liked_icon: ♥
  shuffle_icon: 
  repeat_track_icon: 
  repeat_context_icon: 
  playing_icon: 
  paused_icon: 
  # Sets the window title to "spt - Spotify TUI" via ANSI escape code.
  set_window_title: true
